/* Builds the static frontend for Firebase Hosting into dist/.
 *
 * The Node server templates config into index.html at request time. Firebase
 * Hosting only serves files, so for a split deploy the same templating has to
 * happen here, at build time.
 *
 *   API_BASE=https://outbid.onrender.com \
 *   DATAFAST_WEBSITE_ID=dfid_... DATAFAST_DOMAIN=outbidloll.web.app \
 *   npm run build
 */

import { mkdirSync, readFileSync, writeFileSync, copyFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { renderHtml } from './src/analytics.js';

const ROOT = new URL('.', import.meta.url).pathname;
const SRC  = join(ROOT, 'public');
const OUT  = join(ROOT, 'dist');

const API_BASE = (process.env.API_BASE || '').replace(/\/$/, '');

if (!API_BASE){
  console.error(
    'API_BASE is required.\n\n' +
    'The static build has no backend of its own — it needs the URL of the\n' +
    'deployed API, e.g. API_BASE=https://outbid.onrender.com npm run build\n'
  );
  process.exit(1);
}

try { rmSync(OUT, { recursive: true }); } catch {}
mkdirSync(OUT, { recursive: true });

/* Shared chrome, so the header and footer exist in one place. */
const partial = (name) => readFileSync(join(SRC, name), 'utf8');
const HEAD = partial('_head.html');
const HEADER = partial('_header.html');
const FOOTER = partial('_footer.html');

/* Asset filenames never change, so a browser that cached styles.css under an
   old max-age would keep serving it. Stamp each reference with a hash of the
   file's contents: unchanged files keep their URL and stay cached, changed
   ones get a new URL and are fetched immediately. */
const THEME = process.env.BRAND_THEME || '';
const ASSETS = ['styles.css', 'app.js', 'theme.js', 'icons.js']
  .concat(THEME ? [`theme-${THEME}.css`] : []);
const stamp = Object.fromEntries(ASSETS.map(f => [
  f,
  createHash('sha1').update(readFileSync(join(SRC, f))).digest('hex').slice(0, 8)
]));

function version(html){
  for (const [file, hash] of Object.entries(stamp)){
    html = html.replaceAll(`/${file}"`, `/${file}?v=${hash}"`);
  }
  return html;
}

function assemble(file){
  return version(renderHtml(
    readFileSync(join(SRC, file), 'utf8')
      .replace('<!--HEAD-->', HEAD)
      .replace('<!--HEADER-->', HEADER)
      .replace('<!--FOOTER-->', FOOTER)
  ));
}

for (const page of ['index.html', 'rules.html', 'about.html', 'categories.html']){
  writeFileSync(join(OUT, page), assemble(page));
}

/* Config is a separate file so index.html stays cacheable and the API origin
   is visible in one obvious place rather than buried in the bundle. */
writeFileSync(join(OUT, 'config.js'),
  `/* generated by build.js — do not edit */\n` +
  `window.__CONFIG__ = ${JSON.stringify({ apiBase: API_BASE }, null, 2)};\n`
);

for (const file of ASSETS){
  copyFileSync(join(SRC, file), join(OUT, file));
}

console.log(`built dist/ → API ${API_BASE}`);
console.log('deploy with: firebase deploy --only hosting');
