/* Builds the static frontend for Firebase Hosting into dist/.
 *
 * The Node server templates config into index.html at request time. Firebase
 * Hosting only serves files, so for a split deploy the same templating has to
 * happen here, at build time.
 *
 *   API_BASE=https://outbit-api.onrender.com \
 *   DATAFAST_WEBSITE_ID=dfid_... DATAFAST_DOMAIN=outbit.web.app \
 *   npm run build
 */

import { mkdirSync, readFileSync, writeFileSync, copyFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { renderHtml } from './src/analytics.js';

const ROOT = new URL('.', import.meta.url).pathname;
const SRC  = join(ROOT, 'public');
const OUT  = join(ROOT, 'dist');

const API_BASE = (process.env.API_BASE || '').replace(/\/$/, '');

if (!API_BASE){
  console.error(
    'API_BASE is required.\n\n' +
    'The static build has no backend of its own — it needs the URL of the\n' +
    'deployed API, e.g. API_BASE=https://outbit-api.onrender.com npm run build\n'
  );
  process.exit(1);
}

try { rmSync(OUT, { recursive: true }); } catch {}
mkdirSync(OUT, { recursive: true });

/* index.html goes through the same templating the server uses. */
const html = renderHtml(readFileSync(join(SRC, 'index.html'), 'utf8'));
writeFileSync(join(OUT, 'index.html'), html);

/* Config is a separate file so index.html stays cacheable and the API origin
   is visible in one obvious place rather than buried in the bundle. */
writeFileSync(join(OUT, 'config.js'),
  `/* generated by build.js — do not edit */\n` +
  `window.__CONFIG__ = ${JSON.stringify({ apiBase: API_BASE }, null, 2)};\n`
);

for (const file of ['styles.css', 'app.js']){
  copyFileSync(join(SRC, file), join(OUT, file));
}

console.log(`built dist/ → API ${API_BASE}`);
console.log('deploy with: firebase deploy --only hosting');
